version: "3.8"

# ============================================
# Docker Compose pour tous les microservices
# Jour 4 - Communication entre Microservices
# ============================================

services:

  # ============================================
  # Base de données PostgreSQL pour Product Service
  # ============================================
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    hostname: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
      - ./product-service/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U productuser -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # ============================================
  # Base de données PostgreSQL pour Order Service
  # ============================================
  order-db:
    image: postgres:15-alpine
    container_name: order-db
    hostname: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderuser -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # ============================================
  # Base de données PostgreSQL pour Order Service
  # ============================================
  commande-db:
    image: postgres:15-alpine
    container_name: commande-db
    hostname: commande-db
    environment:
      POSTGRES_DB: commandedb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5435:5432"
    volumes:
      - commande_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orderuser -d orderdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped



# ============================================
# Volumes
# ============================================
volumes:
  product_db_data:
    driver: local
  order_db_data:
    driver: local
  commande_db_data:
    driver: local

# ============================================
# Networks
# ============================================
networks:
  microservices-network:
    driver: bridge
    name: microservices-network
