services:


  # Application Product Service
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productdb
      SPRING_DATASOURCE_USERNAME: productuser
      SPRING_DATASOURCE_PASSWORD: productpass
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8081"

    networks:
      - product-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


networks:
  product-network:
    driver: bridge
